### ISSUE TITLE
no greeter.service

### ISSUE THREAD

**Issue by Hoss3inf** [moleculerjs/moleculer-realworld-example-app#4]
hi there,
in unit tests, the following service has been required:
```
const TestService = require("../../services/greeter.service");
```
meanwhile, there is no such service in `/services` folder.
I have added the `greeter.service.js` from the demo project and it worked.
should I make a pull request?

**Comment by icebob** [comment]
This spec file in tests just an example, not related to this project.

**Comment by Hoss3inf** [comment]
so, is there anything I could do to make it better? I want to start contributing on moleculer framework.

**Comment by icebob** [comment]
I appreciate it. I have a wishlist for Moleculer :) https://github.com/moleculerjs/moleculer/issues/100
